parameters:
- name: buildSteps
  type: stepList
  default: []
- name: publishArtifact
  type: string
  default: ''
  
stages:
- stage: secure_buildstage
  jobs:
  - job: 
    pool:
      vmImage: 'ubuntu-16.04'    
    steps:
    - script: echo Place holder for before the build 
      displayName: 'Pre-build (Template)'

    - ${{ each step in parameters.buildSteps }}:
      - ${{ each pair in step }}:
          ${{ pair.key }}: ${{ pair.value }}       

    - script: echo Running Veracode
      displayName: 'Security Scan (Template)'
    - ${{ if ne(parameters.publishArtifact, '' ) }}:
      - template: /uses/publishArtifactory.yml
        parameters: 
          packageName: ${{parameters.publishArtifact}}
          packageVersion: 1.2.3
