parameters:
- name: steps
  type: stepList
  default: []
- name: publishArtifact
  type: string
  default: ''
  
stages:
- stage: secure_buildstage
  jobs:
  - job: 
    pool:
      vmImage: 'ubuntu-16.04'    
    steps:
    - script: echo Place holder for before the build 
      displayName: 'Base: Pre-build'

    - ${{ each step in parameters.steps }}:
      - ${{ each pair in step }}:
        ${{ pair.key }}: ${{ pair.value }}       

    - script: echo Running Veracode
      displayName: 'Base: Security Scan'
    - ${{ if ne(parameters.publishArtifact, '' ) }}:
      - script: echo Publishing artifact ${{parameters.publishArtifact}} to Artifactory
